### ISSUE TITLE
start herbe in xinitrc

### ISSUE THREAD

**Issue by haluk** [dudik/herbe#13]
I could see the notification window if I run:

`herbe "Notification body" && echo "This is an action"`

Then, I added `herbe &` in my `.xinitrc`. I send a notification with `notify-send "Title" "Body"` but can't see the notification window.

**Comment by dudik** [comment]
herbe is not a notification server. It's daemon-less so you don't have to run it in the background. You have to use `herbe "Body"` instead of `notify-send "Body"`.

**Comment by budRich** [comment]
@haluk, you can use tiramisu as the server and have it redirect libnotify events (f.i. notify-send) to herbe, that is probably the most minimal approach.

**Comment by haluk** [comment]
@budRich, could you please provide the link for `tiramisu`?

**Comment by budRich** [comment]
https://github.com/Sweets/tiramisu
