### ISSUE TITLE
How to build on FreeBSD?

### ISSUE THREAD

**Issue by plasmoduck** [dudik/herbe#15]
Hi can you fix so I can compile on FreeBSD. I have Xlib headers installed already.
herbe.c:1:10: fatal error: 'X11/Xlib.h' file not found
#include <X11/Xlib.h>
         ^~~~~~~~~~~~

**Comment by dudik** [comment]
I created a patch: https://github.com/dudik/herbe/pull/16
I don't use FreeBSD anymore, but I tried the patch in a virtual machine and it seemed to work.

**Comment by plasmoduck** [comment]
Thank you

**Comment by plasmoduck** [comment]
I got it built. But how do I get it to show me notifications when I change songs from ncmpcpp or hexchat messages etc like dunst? When I run 'herbe' I get Usage: herbe body.

**Comment by dudik** [comment]
You can use [tiramisu](https://github.com/Sweets/tiramisu) to call herbe, but herbe can't listen for libnotify notifications on it's own. Basically, it only displays text. That's it. I should probably put it somewhere in the README.md.

**Comment by plasmoduck** [comment]
➜  tiramisu git:(master) ✗ ./tiramisu | herbe
Usage: herbe body
^C%

**Comment by dudik** [comment]
I don't use tiramisu so I don't know how to make it work, I just know it's possible.
